#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jun 14, 2018 03:05:16 AM


import sys
import fetch as WORK

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def twitter_analyze(Class_Sentiment):
    OBJ = Class_Sentiment
    text = OBJ.in_twitter.get()
    print(text)
    msg = "Sentiment of Twitter" + text + "\n\n"

    OBJ.Output.configure(text=msg)

    out = WORK.main(text)

    msg = msg + out[0] + out[1]

    OBJ.Output.configure(text=msg)

def statement_analyze(Class_Sentiment):
    OBJ = Class_Sentiment
    print("statement")

if __name__ == '__main__':
    import project_gui
    project_gui.vp_start_gui()


