#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jun 14, 2018 03:05:31 AM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import project_gui_support as SM

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Sentiment_Analysis (root)
    SM.init(root, top)
    root.mainloop()

w = None
def create_Sentiment_Analysis(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Sentiment_Analysis (w)
    SM.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Sentiment_Analysis():
    global w
    w.destroy()
    w = None


class Sentiment_Analysis:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Courier 10 Pitch} -size 15 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font11 = "-family {Comic Sans MS} -size 15 -weight bold -slant"  \
            " roman -underline 0 -overstrike 0"
        font12 = "-family {Courier New} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Courier 10 Pitch} -size 18 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("895x783+479+127")
        top.title("Sentiment Analysis")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.01, rely=0.01, relheight=0.98, relwidth=0.98)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(width=875)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.02, rely=0.01, height=51, width=839)
        self.Label1.configure(font=font9)
        self.Label1.configure(text='''Sentiment Analysis''')
        self.Label1.configure(width=839)

        self.Frame2 = Frame(self.Frame1)
        self.Frame2.place(relx=0.03, rely=0.12, relheight=0.84, relwidth=0.93)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(width=815)

        self.Output = Message(self.Frame2)
        self.Output.place(relx=0.53, rely=0.02, relheight=0.97, relwidth=0.46)
        self.Output.configure(font=font12)
        self.Output.configure(text='''Output''')
        self.Output.configure(width=372)

        self.Label2 = Label(self.Frame2)
        self.Label2.place(relx=0.04, rely=0.09, height=31, width=279)
        self.Label2.configure(font=font10)
        self.Label2.configure(text='''Analyze Twitter Data''')
        self.Label2.configure(width=279)

        self.in_twitter = Entry(self.Frame2)
        self.in_twitter.place(relx=0.04, rely=0.17,height=33, relwidth=0.35)
        self.in_twitter.configure(background="white")
        self.in_twitter.configure(font="TkFixedFont")
        self.in_twitter.configure(width=286)

        self.Button1 = Button(self.Frame2)
        self.Button1.place(relx=0.15, rely=0.25, height=39, width=102)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(font=font11)
        self.Button1.configure(text='''Analyze''')
        self.Button1.configure(width=99)
        self.Button1.configure(command = lambda : SM.twitter_analyze(self))

        self.Label3 = Label(self.Frame2)
        self.Label3.place(relx=0.04, rely=0.42, height=51, width=279)
        self.Label3.configure(font=font10)
        self.Label3.configure(text='''Analyze Statement''')
        self.Label3.configure(width=279)

        self.in_text = Entry(self.Frame2)
        self.in_text.place(relx=0.04, rely=0.53,height=33, relwidth=0.35)
        self.in_text.configure(background="white")
        self.in_text.configure(font="TkFixedFont")
        self.in_text.configure(width=286)

        self.Button2 = Button(self.Frame2)
        self.Button2.place(relx=0.15, rely=0.6, height=39, width=106)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(font=font11)
        self.Button2.configure(text='''Analyze''')
        self.Button2.configure(width=106)
        self.Button2.configure(command = lambda : SM.statement_analyze(self))






if __name__ == '__main__':
    vp_start_gui()



